baseURL = "https://raditian-hugo.radity.com/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"
[[menu.footer]]
URL = "#contact"
name = "Contact"
weight = 3
[[menu.footer]]
URL = "#portfolio"
name = "Portfolio"
weight = 2
[[menu.footer]]
URL = "#about"
name = "About"
weight = 1
[[menu.header]]
URL = "#contact"
name = "Contact"
weight = 3
[[menu.header]]
URL = "#portfolio"
name = "Portfolio"
weight = 2
[[menu.header]]
URL = "#about"
name = "About"
weight = 1
[params]
googleTagManagerID = "GTM-000000"
[params.footer]
copyright = "© Raditian. All rights reserved."
[params.footer.radity_logo]
_2x = "img/general/design-and-code-radity@2x.png"
alt = "Design & Code - Radity"
x = "img/general/design-and-code-radity.png"
[params.logo]
text1 = "Andreas"
text2 = "Ellure"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"
